### ISSUE TITLE
Wrong spring/security-config.xml namespace?

### ISSUE THREAD

**Issue by rafassmail** [spring-projects/spring-webflow-samples#35]
Hello,

When running the webflow-showcase I get this error trace.

Could be wrong the security-config.xml schema declaration in master?

Replacing spring-security-3.2.xsd by spring-security-4.0.xsd it works.

Thanks
Rafa

INFO : org.springframework.security.core.SpringSecurityCoreVersion - You are running with Spring Security Core 4.0.1.RELEASE
INFO : org.springframework.security.config.SecurityNamespaceHandler - Spring Security 'config' module version is 4.0.1.RELEASE
ERROR: org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from relative location [security-config.xml]
Offending resource: ServletContext resource [/WEB-INF/spring/root-context.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema with Spring Security 3.2. Please update your schema declarations to the 3.2 schema.
Offending resource: ServletContext resource [/WEB-INF/spring/security-config.xml]

**Comment by rstoyanchev** [comment]
This should be fixed now. Thanks for reporting it.
