### ISSUE TITLE
how can wo do for share the session of webflow  ( share the session of webflow with diffrent tomcat)

### ISSUE THREAD

**Issue by liuliangbin** [spring-projects/spring-webflow-samples#43]
we want to deploy three instances tomcat of spring webflow application. (diffrention server ip and port)  and   load  balance with nigix .
we share the tomcat seesion with redis.

but  the spring webflow do not share the session each other applition.

could you tell us , how can wo do for share the session of webflow .

**Comment by rstoyanchev** [comment]
https://jira.spring.io/browse/SWF-1720.
